# Currency settings
CURRENCY_SYMBOL = "D\U000000A2"
CURRENCY_NAME_SINGULAR = "DCoin"
CURRENCY_NAME_PLURAL = "DCoins"

# Economy profile settings
STARTING_MONEY = 15
COLLECTION_MONEY = 5

# Lottery settings
LOTTERY_NUMBERS_IN_POOL = 17
LOTTERY_NUMBERS_TO_DRAW = 10
LOTTERY_PRIZE_DICTIONARY = {10: 100, 9: 50, 8: 15, 7: 10}
LOTTERY_MAX_GAMES_ALLOWED = 15
LOTTERY_COST = 5